name: Framework Python

on:
  push:
    branches:
      - main
      - 'release/framework-*'
  pull_request:
    branches:
      - main
      - 'release/framework-*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      framework: ${{ steps.filter.outputs.framework }}
      ex_bench: ${{ steps.filter.outputs.ex_bench }}  # Examples and Benchmarks
    steps:
      - uses: actions/checkout@v5

      - name: Filter changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            framework:
              - 'framework/**/*'
              - 'dev/devtool/**'
              - 'dev/pyproject.toml'
              - 'dev/uv.lock'
              - '.github/workflows/framework-test.yml'
            ex_bench:
              - 'examples/**/*'
              - 'benchmarks/**/*'
              - 'dev/test.sh'
              - '.github/workflows/framework-test.yml'

  framework_checks:
    runs-on: ubuntu-22.04
    needs: changes
    strategy:
      fail-fast: true
      matrix:
        include:
          - task: quality
            name: Quality
            python: '3.11'
          - task: quality
            name: Quality
            python: '3.12'
          - task: quality
            name: Quality
            python: '3.13'
          - task: pytest
            name: Pytest
            python: '3.11'
          - task: pytest
            name: Pytest
            python: '3.12'
          - task: pytest
            name: Pytest
            python: '3.13'

    name: ${{ matrix.name }} (Python ${{ matrix.python }})

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Bootstrap
        if: ${{ (matrix.task == 'quality' && needs.changes.outputs.framework == 'true') || (matrix.task == 'pytest' && (needs.changes.outputs.framework == 'true' || needs.changes.outputs.ex_bench == 'true')) }}
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python }}
      - name: Prepare framework
        if: ${{ (matrix.task == 'quality' && needs.changes.outputs.framework == 'true') || (matrix.task == 'pytest' && (needs.changes.outputs.framework == 'true' || needs.changes.outputs.ex_bench == 'true')) }}
        run: ./framework/dev/prepare-framework.sh
      - name: Cache mypy
        if: ${{ matrix.task == 'quality' && needs.changes.outputs.framework == 'true' }}
        uses: actions/cache@v4
        with:
          path: framework/.mypy_cache
          key: mypy-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('framework/pyproject.toml', 'framework/uv.lock') }}-${{ github.sha }}
          restore-keys: |
            mypy-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('framework/pyproject.toml', 'framework/uv.lock') }}-
      - name: Install dependencies
        if: ${{ (matrix.task == 'quality' && needs.changes.outputs.framework == 'true') || (matrix.task == 'pytest' && (needs.changes.outputs.framework == 'true' || needs.changes.outputs.ex_bench == 'true')) }}
        run: |
          cd framework
          uv sync --python=${{ matrix.python }} --locked --all-extras --all-groups
      - name: Check if protos need recompilation
        if: ${{ matrix.task == 'quality' && needs.changes.outputs.framework == 'true' }}
        run: |
          cd framework
          uv run --no-sync ./dev/check-protos.sh
      - name: Check if migrations are up to date
        if: ${{ matrix.task == 'quality' && matrix.python == '3.11' && needs.changes.outputs.framework == 'true' }}
        run: |
          cd framework
          uv run --no-sync ./dev/check-migrations.sh
      - name: Lint and static checks
        if: ${{ matrix.task == 'quality' && needs.changes.outputs.framework == 'true' }}
        env:
          RUN_PYTEST: 'false'
        run: |
          cd framework
          uv run --no-sync ./dev/test.sh
      - name: Test
        if: ${{ matrix.task == 'pytest' && needs.changes.outputs.framework == 'true' }}
        run: |
          cd framework
          RAY_ENABLE_UV_RUN_RUNTIME_ENV=0 uv run --no-sync python -m pytest --cov=py/flwr --durations=25 --durations-min=0.5
      - name: Check benchmarks and examples
        if: ${{ matrix.task == 'pytest' && needs.changes.outputs.ex_bench == 'true' }}
        run: |
          cd framework
          uv run --no-sync ../dev/test.sh
