# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add primary task metadata to run and task tables.

Revision ID: 8253e456d570
Revises: dee9b802b5c9
Create Date: 2026-04-27 13:00:44.155029
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "8253e456d570"
down_revision: str | Sequence[str] | None = "dee9b802b5c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("primary_task_id", sa.BigInteger(), nullable=True)
        )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sub_status",
                sa.String(),
                server_default=sa.text("''"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "details",
                sa.String(),
                server_default=sa.text("''"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("details")
        batch_op.drop_column("sub_status")

    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_column("primary_task_id")

    # ### end Alembic commands ###
